package com.artishoepalace.pdfmaker

import android.content.Context
import android.content.Intent
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

@Composable fun V2BottomNav(tab:Int,p:V2Palette,onSelect:(Int)->Unit){ Surface(color=p.card,shadowElevation=8.dp){ Row(Modifier.fillMaxWidth().navigationBarsPadding().height(62.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceAround){ V2Nav("Home",Icons.Default.Home,tab==0,p){onSelect(0)}; Box(Modifier.size(48.dp).clip(CircleShape).background(p.gold).clickable{onSelect(2)},contentAlignment=Alignment.Center){Icon(Icons.Default.Add,null,tint=Color.White)}; V2Nav("Files",Icons.Default.Description,tab==1,p){onSelect(1)} } } }
@Composable private fun V2Nav(s:String,i:ImageVector,on:Boolean,p:V2Palette,c:()->Unit){Column(Modifier.width(90.dp).clickable{c()},horizontalAlignment=Alignment.CenterHorizontally){Icon(i,null,tint=if(on)p.gold else p.muted,modifier=Modifier.size(23.dp));Text(s,fontSize=10.sp,color=if(on)p.darkGold else p.muted,fontWeight=if(on)FontWeight.Bold else FontWeight.Medium)}}

@Composable fun V2Home(context:Context,refresh:Int,p:V2Palette,settings:()->Unit,searchOut:(String)->Unit,image:()->Unit,scan:()->Unit,importPdf:()->Unit,compress:()->Unit,jpg:()->Unit,merge:()->Unit,docx:()->Unit,more:()->Unit,rescan:()->Unit){
 var searching by remember{mutableStateOf(false)};var q by remember{mutableStateOf("")};val docs by produceState(emptyList<V2Doc>(),refresh,q){value=withContext(Dispatchers.IO){v2ListDocs(context).filter{q.isBlank()||it.name.contains(q,true)}.take(4)}}
 LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(bottom=12.dp)){item{Column(Modifier.padding(16.dp,8.dp)){Row(verticalAlignment=Alignment.CenterVertically){Image(painterResource(R.drawable.pdf_logo),null,modifier=Modifier.size(42.dp).clip(RoundedCornerShape(12.dp)));Spacer(Modifier.width(9.dp));if(searching){OutlinedTextField(q,{q=it;searchOut(it)},modifier=Modifier.weight(1f).height(50.dp),singleLine=true,placeholder={Text("Search PDFs")});IconButton({searching=false;q="";searchOut("")}){Icon(Icons.Default.Close,null)}}else{Text("Home",fontSize=26.sp,fontWeight=FontWeight.ExtraBold,color=p.darkGold,modifier=Modifier.weight(1f));IconButton({searching=true}){Icon(Icons.Default.Search,null,tint=p.text)};IconButton(settings){Icon(Icons.Default.Settings,null,tint=p.text)}}};Spacer(Modifier.height(14.dp));val a=listOf(Triple("Image to PDF",Icons.Default.PictureAsPdf,image),Triple("Smart Scan",Icons.Default.DocumentScanner,scan),Triple("Import PDF",Icons.Default.Folder,importPdf),Triple("Compress",Icons.Default.Compress,compress),Triple("PDF to JPG",Icons.Default.Image,jpg),Triple("Merge PDF",Icons.Default.CallMerge,merge),Triple("DOCX to PDF",Icons.Default.Description,docx),Triple("More",Icons.Default.Apps,more));a.chunked(4).forEachIndexed{r,row->Row(Modifier.fillMaxWidth().padding(bottom=13.dp),horizontalArrangement=Arrangement.SpaceBetween){row.forEachIndexed{x,t->V2Circle(t.first,t.second,p,r*4+x,t.third)}}}}};item{Surface(color=p.card,shape=RoundedCornerShape(topStart=26.dp,topEnd=26.dp),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text("All PDFs (${docs.size})",fontSize=21.sp,fontWeight=FontWeight.Bold,color=p.darkGold,modifier=Modifier.weight(1f));IconButton(rescan){Icon(Icons.Default.Refresh,null,tint=p.gold)}};if(docs.isEmpty())Text("Scanning device PDFs… Add a scan folder in Settings if Android restricts a location.",color=p.muted,fontSize=12.sp,modifier=Modifier.padding(vertical=20.dp));docs.forEach{V2FileRow(context,it,p,rescan)}}}} }
}
@Composable private fun V2Circle(s:String,i:ImageVector,p:V2Palette,n:Int,c:()->Unit){val cs=listOf(Color(0xFFFF4D6D),Color(0xFF4E82FF),Color(0xFFFFA928),Color(0xFF7A5AF8),Color(0xFF20A98B),Color(0xFFFF8B2B),Color(0xFF4E82FF),p.gold);Column(Modifier.width(78.dp).clickable{c()},horizontalAlignment=Alignment.CenterHorizontally){Surface(shape=CircleShape,color=p.card,modifier=Modifier.size(62.dp),border=BorderStroke(1.dp,p.gold.copy(.18f)),shadowElevation=2.dp){Box(contentAlignment=Alignment.Center){Icon(i,null,tint=cs[n%cs.size],modifier=Modifier.size(28.dp))}};Spacer(Modifier.height(6.dp));Text(s,color=p.text,fontSize=10.5.sp,fontWeight=FontWeight.SemiBold,maxLines=2,overflow=TextOverflow.Ellipsis)}}

@Composable fun V2Tools(p:V2Palette,back:()->Unit,convert:List<V2Tool>,popular:List<V2Tool>,edit:List<V2Tool>){LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(bottom=24.dp)){item{Row(Modifier.padding(10.dp,8.dp),verticalAlignment=Alignment.CenterVertically){IconButton(back){Icon(Icons.Default.ArrowBack,null,tint=p.text)};Text("More PDF Tools",fontSize=21.sp,fontWeight=FontWeight.Bold,color=p.darkGold)}};item{Surface(shape=RoundedCornerShape(20.dp),color=p.card,modifier=Modifier.fillMaxWidth().padding(horizontal=14.dp)){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.AutoAwesome,null,tint=p.gold);Spacer(Modifier.width(12.dp));Column{Text("Power tools",fontWeight=FontWeight.Bold,color=p.text);Text("Convert, scan, AI-read, edit and secure PDFs",fontSize=12.sp,color=p.muted)}}}};item{V2Section("Convert & Export",convert,p)};item{V2Section("Scan & AI",popular,p)};item{V2Section("Edit & Security",edit,p)}}}
@Composable private fun V2Section(title:String,a:List<V2Tool>,p:V2Palette){Column(Modifier.padding(14.dp,10.dp)){Text(title,fontSize=18.sp,fontWeight=FontWeight.Bold,color=p.darkGold,modifier=Modifier.padding(vertical=8.dp));a.chunked(3).forEach{row->Row(Modifier.fillMaxWidth().padding(bottom=10.dp),horizontalArrangement=Arrangement.spacedBy(10.dp)){row.forEach{t->Surface(shape=RoundedCornerShape(18.dp),color=p.card,modifier=Modifier.weight(1f).height(112.dp).clickable{t.action()},border=BorderStroke(1.dp,p.gold.copy(.16f))){Column(horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Icon(t.icon,null,tint=t.tint,modifier=Modifier.size(30.dp));Spacer(Modifier.height(8.dp));Text(t.label,color=p.text,fontSize=11.5.sp,fontWeight=FontWeight.SemiBold,maxLines=2)}}};repeat(3-row.size){Spacer(Modifier.weight(1f))}}}}}

@Composable fun V2Files(context:Context,refresh:Int,p:V2Palette,sort:V2Sort,desc:Boolean,globalSearch:String,searchOut:(String)->Unit,settings:()->Unit,sortClick:()->Unit,rescan:()->Unit){val prefs=remember{context.getSharedPreferences("pdf_maker",Context.MODE_PRIVATE)};var filter by remember{mutableStateOf(V2Filter.ALL)};var searching by remember{mutableStateOf(false)};var q by remember(globalSearch){mutableStateOf(globalSearch)};var local by remember{mutableIntStateOf(0)};val fav=remember(refresh,local){prefs.getStringSet("favorites",emptySet())?:emptySet()};val docs by produceState(emptyList<V2Doc>(),refresh,local,sort,desc,filter,q,fav){value=withContext(Dispatchers.IO){var a=v2ListDocs(context);if(q.isNotBlank())a=a.filter{it.name.contains(q,true)};a=when(filter){V2Filter.ALL->a;V2Filter.RECENT->a.filter{System.currentTimeMillis()-it.modified<=604800000L};V2Filter.FAVORITES->a.filter{it.key in fav}};a=when(sort){V2Sort.SIZE->a.sortedBy{it.size};V2Sort.NAME->a.sortedBy{it.name.lowercase()};V2Sort.MODIFIED->a.sortedBy{it.modified}};if(desc)a.reversed() else a}};Column(Modifier.fillMaxSize().padding(horizontal=14.dp,vertical=7.dp)){Row(verticalAlignment=Alignment.CenterVertically){if(searching){OutlinedTextField(q,{q=it;searchOut(it)},modifier=Modifier.weight(1f).height(50.dp),singleLine=true);IconButton({searching=false;q="";searchOut("")}){Icon(Icons.Default.Close,null)}}else{Text("Files",fontSize=26.sp,fontWeight=FontWeight.ExtraBold,color=p.darkGold,modifier=Modifier.weight(1f));IconButton({searching=true}){Icon(Icons.Default.Search,null)};IconButton(rescan){Icon(Icons.Default.Refresh,null)};IconButton(sortClick){Icon(Icons.Default.Sort,null)};IconButton(settings){Icon(Icons.Default.Settings,null)}}};Row(horizontalArrangement=Arrangement.spacedBy(7.dp),modifier=Modifier.padding(vertical=10.dp)){FilterChip(filter==V2Filter.ALL,{filter=V2Filter.ALL},{Text("All")});FilterChip(filter==V2Filter.RECENT,{filter=V2Filter.RECENT},{Text("Recent")});FilterChip(filter==V2Filter.FAVORITES,{filter=V2Filter.FAVORITES},{Text("Favorites")})};Text("${docs.size} PDF files",fontSize=11.sp,color=p.muted,modifier=Modifier.padding(bottom=7.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(9.dp),contentPadding=PaddingValues(bottom=14.dp)){if(docs.isEmpty())item{Text(if(filter==V2Filter.FAVORITES)"No favorites yet. Tap ☆ on any PDF." else "No PDFs visible yet. Rescan or add a scan folder.",color=p.muted,modifier=Modifier.padding(18.dp))};items(docs,key={it.key}){d->V2FileRow(context,d,p){local++;rescan()}}}}}

@Composable private fun V2FileRow(context:Context,doc:V2Doc,p:V2Palette,refresh:()->Unit){val prefs=remember{context.getSharedPreferences("pdf_maker",Context.MODE_PRIVATE)};var menu by remember{mutableStateOf(false)};var favorite by remember(doc.key){mutableStateOf(doc.key in(prefs.getStringSet("favorites",emptySet())?:emptySet()))};Surface(shape=RoundedCornerShape(18.dp),color=p.card,modifier=Modifier.fillMaxWidth().height(104.dp).clickable{v2OpenDoc(context,doc)},border=BorderStroke(1.dp,p.gold.copy(.12f))){Row(Modifier.padding(10.dp),verticalAlignment=Alignment.CenterVertically){Surface(shape=RoundedCornerShape(14.dp),color=p.alt,modifier=Modifier.size(70.dp)){Box(contentAlignment=Alignment.Center){Icon(Icons.Default.PictureAsPdf,null,tint=Color(0xFFFF365F),modifier=Modifier.size(36.dp))}};Column(Modifier.weight(1f).padding(start=12.dp)){Text(doc.name.substringBeforeLast("."),color=p.text,fontSize=14.sp,fontWeight=FontWeight.Bold,maxLines=1,overflow=TextOverflow.Ellipsis);Text("${v2Date(doc.modified)} • ${v2Size(doc.size)}",fontSize=11.sp,color=p.muted);if(doc.pages>0)Text("${doc.pages} pages",fontSize=11.sp,color=p.muted)};IconButton({val s=(prefs.getStringSet("favorites",emptySet())?:emptySet()).toMutableSet();favorite=!favorite;if(favorite)s+=doc.key else s-=doc.key;prefs.edit().putStringSet("favorites",s).apply();refresh()}){Icon(if(favorite)Icons.Default.Star else Icons.Default.StarBorder,null,tint=if(favorite)p.gold else p.muted)};Box{IconButton({menu=true}){Icon(Icons.Default.MoreVert,null,tint=p.muted)};DropdownMenu(menu,{menu=false}){DropdownMenuItem({Text("Open")},{menu=false;v2OpenDoc(context,doc)});DropdownMenuItem({Text("Share")},{menu=false;v2ShareDoc(context,doc)});if(doc.file!=null&&doc.file.absolutePath.startsWith(context.filesDir.absolutePath))DropdownMenuItem({Text("Delete",color=Color(0xFFD32F2F))},{menu=false;if(doc.file.delete())refresh()})}}}}}

@Composable fun V2Settings(context:Context,p:V2Palette,dark:Boolean,onDark:(Boolean)->Unit,back:()->Unit,rescan:()->Unit,addFolder:()->Unit){val prefs=remember{context.getSharedPreferences("pdf_maker",Context.MODE_PRIVATE)};var key by remember{mutableStateOf(prefs.getString("openai_key","").orEmpty())};var model by remember{mutableStateOf(prefs.getString("openai_model","gpt-5.4").orEmpty())};var auto by remember{mutableStateOf(prefs.getBoolean("auto_scan",true))};var json by remember{mutableStateOf(prefs.getBoolean("ai_json",false))};var security by remember{mutableStateOf(prefs.getBoolean("security",false))};val folders=prefs.getStringSet("scan_trees",emptySet())?.size?:0;LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(bottom=24.dp)){item{Row(Modifier.padding(10.dp),verticalAlignment=Alignment.CenterVertically){IconButton(back){Icon(Icons.Default.ArrowBack,null,tint=p.text)};Text("Settings",fontSize=21.sp,fontWeight=FontWeight.Bold,color=p.darkGold)}};item{V2Card(p){V2Action(Icons.Default.Refresh,"Scan device PDFs now",p,rescan);V2Action(Icons.Default.CreateNewFolder,"Add scan folder ($folders)",p,addFolder);V2Toggle(Icons.Default.DocumentScanner,"Auto scan PDFs",auto,p){auto=it;prefs.edit().putBoolean("auto_scan",it).apply()};V2Toggle(Icons.Default.Security,"Security preference",security,p){security=it;prefs.edit().putBoolean("security",it).apply()};V2Toggle(Icons.Default.DarkMode,"Dark mode",dark,p,onDark)}};item{Text("AI Scan",fontSize=17.sp,fontWeight=FontWeight.Bold,color=p.darkGold,modifier=Modifier.padding(18.dp,10.dp));V2Card(p){Text("Use your own OpenAI API key for image/PDF reading. It stays in local app preferences.",fontSize=11.5.sp,color=p.muted);Spacer(Modifier.height(8.dp));OutlinedTextField(key,{key=it},label={Text("OpenAI API key")},visualTransformation=PasswordVisualTransformation(),singleLine=true,modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(7.dp));OutlinedTextField(model,{model=it},label={Text("Model")},singleLine=true,modifier=Modifier.fillMaxWidth());V2Toggle(Icons.Default.DataObject,"Prefer JSON output",json,p){json=it;prefs.edit().putBoolean("ai_json",it).apply()};Button({prefs.edit().putString("openai_key",key.trim()).putString("openai_model",model.trim().ifBlank{"gpt-5.4"}).apply();v2Toast(context,"AI settings saved")},modifier=Modifier.fillMaxWidth().padding(top=8.dp)){Text("Save AI settings")}}};item{V2Card(p){V2Action(Icons.Default.Share,"Share app",p){context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).apply{type="text/plain";putExtra(Intent.EXTRA_TEXT,"PDF Maker")},"Share PDF Maker"))};V2Action(Icons.Default.CleaningServices,"Clear temporary cache",p){context.cacheDir.listFiles()?.forEach{it.deleteRecursively()};v2Toast(context,"Cache cleared")};V2Action(Icons.Default.PrivacyTip,"Privacy",p){v2Toast(context,"Files stay local unless you use AI Scan")};Text("Version 1.2.0",color=p.muted,modifier=Modifier.padding(vertical=12.dp))}}}}
@Composable private fun V2Card(p:V2Palette,c:@Composable ColumnScope.()->Unit){Surface(shape=RoundedCornerShape(20.dp),color=p.card,modifier=Modifier.fillMaxWidth().padding(14.dp,5.dp),border=BorderStroke(1.dp,p.gold.copy(.14f))){Column(Modifier.padding(16.dp),content=c)}}
@Composable private fun V2Action(i:ImageVector,s:String,p:V2Palette,c:()->Unit){Row(Modifier.fillMaxWidth().clickable{c()}.padding(vertical=12.dp),verticalAlignment=Alignment.CenterVertically){Icon(i,null,tint=p.gold);Spacer(Modifier.width(14.dp));Text(s,color=p.text,fontWeight=FontWeight.SemiBold,modifier=Modifier.weight(1f));Icon(Icons.Default.ChevronRight,null,tint=p.muted)}}
@Composable private fun V2Toggle(i:ImageVector,s:String,on:Boolean,p:V2Palette,c:(Boolean)->Unit){Row(Modifier.fillMaxWidth().padding(vertical=8.dp),verticalAlignment=Alignment.CenterVertically){Icon(i,null,tint=p.gold);Spacer(Modifier.width(14.dp));Text(s,color=p.text,fontWeight=FontWeight.SemiBold,modifier=Modifier.weight(1f));Switch(on,c)}}

@OptIn(ExperimentalMaterial3Api::class) @Composable fun V2SortSheet(p:V2Palette,sort:V2Sort,desc:Boolean,setSort:(V2Sort)->Unit,setDesc:(Boolean)->Unit,close:()->Unit){ModalBottomSheet(onDismissRequest=close,containerColor=p.card){Column(Modifier.padding(20.dp,8.dp)){Text("Sort files",fontSize=21.sp,fontWeight=FontWeight.Bold,color=p.darkGold);V2SortRow("File size",Icons.Default.Storage,sort==V2Sort.SIZE,p){setSort(V2Sort.SIZE)};V2SortRow("Name",Icons.Default.InsertDriveFile,sort==V2Sort.NAME,p){setSort(V2Sort.NAME)};V2SortRow("Modified",Icons.Default.EditCalendar,sort==V2Sort.MODIFIED,p){setSort(V2Sort.MODIFIED)};HorizontalDivider();V2SortRow("Ascending",Icons.Default.ArrowUpward,!desc,p){setDesc(false)};V2SortRow("Descending",Icons.Default.ArrowDownward,desc,p){setDesc(true)};Button(close,modifier=Modifier.fillMaxWidth().padding(vertical=14.dp)){Text("Apply")}}}}
@Composable private fun V2SortRow(s:String,i:ImageVector,on:Boolean,p:V2Palette,c:()->Unit){Row(Modifier.fillMaxWidth().clickable{c()}.padding(vertical=11.dp),verticalAlignment=Alignment.CenterVertically){Icon(i,null,tint=p.gold);Spacer(Modifier.width(16.dp));Text(s,color=p.text,fontSize=15.sp,modifier=Modifier.weight(1f));RadioButton(on,c)}}
@Composable fun V2Loading(p:V2Palette){Surface(color=Color.Black.copy(.42f),modifier=Modifier.fillMaxSize()){Box(contentAlignment=Alignment.Center){Card(colors=CardDefaults.cardColors(containerColor=p.card)){Row(Modifier.padding(20.dp),verticalAlignment=Alignment.CenterVertically){CircularProgressIndicator(color=p.gold,modifier=Modifier.size(28.dp));Spacer(Modifier.width(12.dp));Text("AI is reading…",color=p.text)}}}}}
